language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gdebi-core
  - sudo ./utils/build_deps.sh $TRAVIS_BUILD_DIR
script:
  - make -C iptables-extension
  - make -C daemon -j`nproc`
