#!/bin/bash
#
# Target dist: Ubuntu Focal
DIST=focal

if [ ! -d ../../pkg/deb ] ; then
  echo "script needs to be executed at pkg/deb dir" >&2
  exit 1
fi

rm -rf ${DIST}
cp -r debian ${DIST}

# No libbcg729-dev package
sed -i -e '/libbcg729-dev/d' ${DIST}/control

# Update for focal debhelper
sed -i -e 's/debhelper-compat.*/debhelper-compat (= 12),/' ${DIST}/control
# Replace execute_* hooks with old-style overrides
sed -i -e 's/^execute_after_dh_installsystemd:/override_dh_installsystemd:\n\tdh_installsystemd/' ${DIST}/rules
sed -i -e 's/^execute_before_dh_auto_install-indep:/override_dh_auto_install-indep:/' ${DIST}/rules
sed -i -e '/^\tgzip -9 < README.md/a\\n\tdh_auto_install' ${DIST}/rules
# Add dwz override
cat >> ${DIST}/rules <<'EOF'

override_dh_dwz:
	# Disable, as dwz cannot cope with some of the plugins generated.
EOF

# Fix module installation location
rm ${DIST}/rtpengine-iptables.dirs
rm ${DIST}/rtpengine-iptables.install
cat >> ${DIST}/rules <<'EOF'

override_dh_install:
	dh_install
	dh_installdirs -prtpengine-iptables $(XTABLES_DIR)
	rm -f debian/tmp/$(XTABLES_DIR)/libxt_RTPENGINE.so
	install -m 0644 iptables-extension/libxt_RTPENGINE.so debian/rtpengine-iptables/$(XTABLES_DIR)
EOF

if command -v wrap-and-sort &>/dev/null ; then
  wrap-and-sort -sat -d ${DIST}
else
  echo "WARN: wrap-and-sort (Debian package devscripts) not available."
fi

# clean backports scripts
rm -rf ${DIST}/backports
exit 0
