.TH man 1 "17 May 2022" "1.0" "ngcp-rtpengine-recording-nfs-setup man page"
.SH NAME
ngcp\-rtpengine\-recording\-nfs\-setup \- manages NFS mount for ngcp\-rtpengine\-recording\-daemon service
.SH SYNOPSIS
ngcp\-rtpengine\-recording\-nfs\-setup [start|stop]
.SH DESCRIPTION
ngcp\-rtpengine\-recording\-nfs\-setup will mount or unmount the NFS resource needed by ngcp\-rtpengine\-recording\-daemon to properly work.
This program will be called by ngcp\-rtpengine\-recording\-daemon service.
.SH OPTIONS
ngcp\-rtpengine\-recording\-nfs\-setup has no options.
.SH SEE ALSO
rtpengine\-recording(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Victor Seva (vseva@sipwise.com)
