.TH man 1 "17 May 2022" "1.0" "ngcp-rtpengine-iptables-setup man page"
.SH NAME
ngcp\-rtpengine\-iptables\-setup \- manages iptables rules for ngcp\-rtpengine\-daemon service
.SH SYNOPSIS
ngcp\-rtpengine\-iptables\-setup [start|stop]
.SH DESCRIPTION
ngcp\-rtpengine\-iptables\-setup will enable or disable the iptables rules needed by rtpengine to properly work.
This program will be called by ngcp\-rtpengine\-daemon service.
.SH OPTIONS
ngcp\-rtpengine\-iptables\-setup has no options.
.SH SEE ALSO
rtpengine(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Victor Seva (vseva@sipwise.com)
