.TH man 1 "17 May 2022" "1.0" "rtpengine-ng-client man page"
.SH NAME
rtpengine\-ng\-client \- utility for sending client commands to ngcp\-rtpengine\-daemon service
.SH SYNOPSIS
rtpengine\-ng\-client <NG-OPTIONS>
.SH DESCRIPTION
rtpengine\-ng\-client will send NG commands to the specified ngcp\-rtpengine\-daemon service.
This util is mainly used to simulate a client in a development environment.
.SH OPTIONS
See the full list of NG parameters at README.
.SH SEE ALSO
rtpengine(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Victor Seva (vseva@sipwise.com)
